local tags = {
	SPAWN_TAG = "Spawn",
	SPOT_TAG = "Spot",
	NOT_FIRST_TAG = "NotFirst",
	ONLY_FIRST_TAG = "OnlyFirst",
	LOBBYZONE = "LobbyZone",
	GOLDEN_TOILET = "GoldenToilet",
	TOILET_BODY = "ToiletBody",
	TOILET_SEAT = "ToiletSeat",
	TOILET_LID = "ToiletLid",
	TOILET_PARTICLE_PARENT = "ToiletParticleParent",
	Sound_On_Hover = "SoundOnHover",
	Sound_On_Click = "SoundOnClick",
	Sound_On_Click_Flush = "SoundOnClickFlush",
	Sound_On_Visible_Win = "SoundOnVisibleWin",
	Sound_On_Visible_Lose = "SoundOnVisibleLose",
	SHOP_PROXIMITY = "ShopProximity",
}

return tags
